labels_locations: 
  - /Volumes/MML/dailymed_labels/dailymed_1
  - /Volumes/MML/dailymed_labels/dailymed_2
  - /Volumes/MML/dailymed_labels/dailymed_3
  - /Volumes/MML/dailymed_labels/dailymed_4
  - /Volumes/MML/dailymed_labels/dailymed_5

